import React, { useEffect } from "react";
import Swiper from "swiper/bundle";
import "../../../node_modules/swiper/swiper-bundle.min.css";
import "../../Styles/Itam.css";

const CRMSM = () => {
  useEffect(() => {
    const swiper = new Swiper(".swiper", {
      loop: true,
      pagination: {
        el: ".swiper-pagination",
      },
      navigation: {
        nextEl: ".swiper-button-next",
        prevEl: ".swiper-button-prev",
      },
    });
  }, []);
  return (
    <>
      <div className="fam-header">
        
        <p>
          CoRMS offers an intuitive user friendly CRM Service Management product
          that helps track, administer and manage your service to your clients
          who have purchased your product. Its assets tracking capability helps
          you track and link customer with the asset they have purchased; and it
          the asset is within waranty or not. CoRMS’ Service Management module
          helps track and manage service requests with SLA monitoring. It is
          supported by a detailed spares module.
          <br></br><br></br>
          Standard decision support reports such as MTBF and MTTR report are
          generated by this module. Its Spares and Consumables Management module
          tracks their consumption and helps re-order them and manage stock.
          <br></br><br></br>
          Importantly the Service Management module is not limited by the number
          of users. It thus facilitates ease of use and speeds up service
          turnarounds.
        </p>
      </div>
      <div className="fam-main">
        <div class="swiper">
          <div class="swiper-button-next"></div>
          <div class="swiper-button-prev"></div>

          <div class="swiper-wrapper">
            
            <div class="swiper-slide">
              <div class="testimonial__card">
                <br />

                <h2 class="section__header">Service Complaint Management</h2>
                <ul>
                  <li class="text">Service Requests</li>
                  <li class="text">Ticket Generation</li>
                  <li class="text">
                    Approval / Call Allocation &amp; Management
                  </li>
                  <li class="text">
                    Direct call forwarding for assets under warranty/AMC
                  </li>
                  <li class="text">Automatic Service Level escalation</li>
                  <li class="text">Service Call Status Monitoring</li>
                  <li class="text">Call closure</li>
                  <li class="text">Knowledge repository</li>
                  <li class="text">Call history</li>
                  <li class="text">SLA monitoring</li>
                  <li class="text">email escalation</li>
                  <li class="text">Mean Time to Repair (MTTR) Report</li>
                  <li class="text">Mean Time Between Failures (MTBF) Report</li>
                </ul>
              </div>
            </div>
            <div class="swiper-slide">
              <div class="testimonial__card">
                <br />
                <h2 class="section__header">Asset Management Module FAMS</h2>

                <ul>
                  <li class="text">Helps know assets purchased</li>
                  <li class="text">Track their warranty</li>
                  <li class="text">History of the asset service</li>
                </ul>
              </div>
            </div>
            <div class="swiper-slide">
              <div class="testimonial__card">
                <br />
                <h2 class="section__header">Barcode Interface</h2>

                <ul>
                  <li class="text">Generating Barcode labels</li>
                  <li class="text">Input of Barcode data</li>
                  <li class="text">Viewing Asset details using the barcode</li>
                </ul>
              </div>
            </div>
            <div class="swiper-slide">
              <div class="testimonial__card">
                <br />

                <h2 class="section__header">Spares & Consumables Management</h2>

                <ul>
                  <li class="text">Handling Multiple Stores</li>
                  <li class="text">Inter Store transfer</li>
                  <li class="text">Generating POs/ Maintaining PO details</li>
                  <li class="text">Purchase register</li>
                  <li class="text">Indents</li>
                  <li class="text">Rate comparison</li>
                  <li class="text">
                    Tracking consumable levels with alerts for reorder level
                  </li>
                  <li class="text">
                    Consumable request escalation and approval
                  </li>
                  <li class="text">Issue register</li>
                  <li class="text">Refill Management</li>
                  <li class="text">Disposal</li>
                </ul>
              </div>
            </div>
            <div class="swiper-slide">
              <div class="testimonial__card">
                <br />

                <h2 class="section__header">Request Management</h2>

                <ul>
                  <li class="text">
                    User request for new asset, upgradation,Movement, Service
                    request and Consumables
                  </li>
                  <li class="text">Rule based approval</li>
                </ul>
              </div>
            </div>
          </div>

          <div class="swiper-pagination"></div>
        </div>
        <div className="fam-main-right">
          <img src="../ITAM.jpg" alt="" />
        </div>
      </div>
    </>
  );
};

export default CRMSM;
